### ISSUE TITLE
duplicitni zaznamy v TABB.rds

### ISSUE THREAD

**Issue by hanel** [KVHEM/Sucho_obecne#3]
napr. b[TO=='BER_0550', length(unique(FROM))] != nrow(b[TO=='BER_0550'])

**Comment by hanel** [comment]
lze vyresit nejak takto:

b = data.table(readRDS('TABB.Rds'))
b = b[, .(FROM = unique(FROM), DIST = DIST[1]), by = TO]

prosim, finalni verzi udelej takto (tj. aby to byl data.table, a aby tam nebyly duplicity)

**Comment by petr-pavlik** [comment]
Doplněno na owc/used_data: TABA, TABB.
